### ISSUE TITLE
Invalid link: http://localhost:8080/blog/ 

### ISSUE THREAD

**Issue by captain-melanie** [Lrtwjhs/Java-Projects#1]
Hi, 
I wasn't able to access the blog by http://localhost:8080/blog/
I guess it is because the "blog" file does not exist? though http://localhost:8080/WebRoot/aboutus.jsp is accessible.
And, the signin page threw a "HTTP Status 500" error when I tried to log in.

**Comment by Lrtwjhs** [comment]
Thank for your Issues, sorry to bring you confused.
First issue, when you copy the Blog/WebRoot to /usr/local/tomcat/webapps,  you should rename the file to Blog; Second issue, I think you maybe have something wrong  in connecting to the mysql database.
So, I have fixed my project and made a live demo, hope this helps.

**Comment by melanie0926** [comment]
I see I see. I did import the sql file into my database, however, I didn't modify the password. That was why it got errors connecting to the db.

And, it's so pleasing to see a live demo. The site, the layout and the appearance, are exactly what I wanted. I'm looking forward to build a similar site. Thank you so much!
